---
- name: select mq server list
  set_fact:
    mq_ip_list: "{{value}}"
  with_items: "{{mq_list}}" 
  loop_control:
    index_var: index
    loop_var: value
  when: (index + 1) == router_id

# tasks file for copy
- name: "push server a {{router_id}}.{{zone_id}}.{{server_a_info.type_id}}.1"    
  copy:
    src: '{{src_path}}{{copy_info.src}}'
    dest: '{{copy_dest_path}}{{copy_info.dest}}'
  with_items:
    '{{server_a_info.files}}'
  loop_control:
    loop_var: copy_info        
  tags: [push, update, push_server_a, update_server_a]  
