// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: say_hello.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "say_hello.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace proto {
namespace Test {
class SayHelloReqDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<SayHelloReq> {
} _SayHelloReq_default_instance_;
class SayHelloRspDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<SayHelloRsp> {
} _SayHelloRsp_default_instance_;

namespace protobuf_say_5fhello_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SayHelloReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SayHelloReq, content_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SayHelloRsp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SayHelloRsp, content_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(SayHelloReq)},
  { 6, -1, sizeof(SayHelloRsp)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_SayHelloReq_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_SayHelloRsp_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "say_hello.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace

void TableStruct::Shutdown() {
  _SayHelloReq_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _SayHelloRsp_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _SayHelloReq_default_instance_.DefaultConstruct();
  _SayHelloRsp_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\017say_hello.proto\022\nproto.Test\"\036\n\013SayHell"
      "oReq\022\017\n\007content\030\001 \001(\t\"\036\n\013SayHelloRsp\022\017\n\007"
      "content\030\001 \001(\tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 101);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "say_hello.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_say_5fhello_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SayHelloReq::kContentFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SayHelloReq::SayHelloReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_say_5fhello_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.Test.SayHelloReq)
}
SayHelloReq::SayHelloReq(const SayHelloReq& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  content_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.content().size() > 0) {
    content_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.content_);
  }
  // @@protoc_insertion_point(copy_constructor:proto.Test.SayHelloReq)
}

void SayHelloReq::SharedCtor() {
  content_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

SayHelloReq::~SayHelloReq() {
  // @@protoc_insertion_point(destructor:proto.Test.SayHelloReq)
  SharedDtor();
}

void SayHelloReq::SharedDtor() {
  content_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SayHelloReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SayHelloReq::descriptor() {
  protobuf_say_5fhello_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_say_5fhello_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SayHelloReq& SayHelloReq::default_instance() {
  protobuf_say_5fhello_2eproto::InitDefaults();
  return *internal_default_instance();
}

SayHelloReq* SayHelloReq::New(::google::protobuf::Arena* arena) const {
  SayHelloReq* n = new SayHelloReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SayHelloReq::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.Test.SayHelloReq)
  content_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool SayHelloReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.Test.SayHelloReq)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string content = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_content()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->content().data(), this->content().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.Test.SayHelloReq.content"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.Test.SayHelloReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.Test.SayHelloReq)
  return false;
#undef DO_
}

void SayHelloReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.Test.SayHelloReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string content = 1;
  if (this->content().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->content().data(), this->content().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.Test.SayHelloReq.content");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->content(), output);
  }

  // @@protoc_insertion_point(serialize_end:proto.Test.SayHelloReq)
}

::google::protobuf::uint8* SayHelloReq::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto.Test.SayHelloReq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string content = 1;
  if (this->content().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->content().data(), this->content().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.Test.SayHelloReq.content");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->content(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:proto.Test.SayHelloReq)
  return target;
}

size_t SayHelloReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.Test.SayHelloReq)
  size_t total_size = 0;

  // string content = 1;
  if (this->content().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->content());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SayHelloReq::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.Test.SayHelloReq)
  GOOGLE_DCHECK_NE(&from, this);
  const SayHelloReq* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SayHelloReq>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.Test.SayHelloReq)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.Test.SayHelloReq)
    MergeFrom(*source);
  }
}

void SayHelloReq::MergeFrom(const SayHelloReq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.Test.SayHelloReq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.content().size() > 0) {

    content_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.content_);
  }
}

void SayHelloReq::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.Test.SayHelloReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SayHelloReq::CopyFrom(const SayHelloReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.Test.SayHelloReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SayHelloReq::IsInitialized() const {
  return true;
}

void SayHelloReq::Swap(SayHelloReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SayHelloReq::InternalSwap(SayHelloReq* other) {
  content_.Swap(&other->content_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SayHelloReq::GetMetadata() const {
  protobuf_say_5fhello_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_say_5fhello_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SayHelloReq

// string content = 1;
void SayHelloReq::clear_content() {
  content_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& SayHelloReq::content() const {
  // @@protoc_insertion_point(field_get:proto.Test.SayHelloReq.content)
  return content_.GetNoArena();
}
void SayHelloReq::set_content(const ::std::string& value) {
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.Test.SayHelloReq.content)
}
#if LANG_CXX11
void SayHelloReq::set_content(::std::string&& value) {
  
  content_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.Test.SayHelloReq.content)
}
#endif
void SayHelloReq::set_content(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.Test.SayHelloReq.content)
}
void SayHelloReq::set_content(const char* value, size_t size) {
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.Test.SayHelloReq.content)
}
::std::string* SayHelloReq::mutable_content() {
  
  // @@protoc_insertion_point(field_mutable:proto.Test.SayHelloReq.content)
  return content_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* SayHelloReq::release_content() {
  // @@protoc_insertion_point(field_release:proto.Test.SayHelloReq.content)
  
  return content_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void SayHelloReq::set_allocated_content(::std::string* content) {
  if (content != NULL) {
    
  } else {
    
  }
  content_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), content);
  // @@protoc_insertion_point(field_set_allocated:proto.Test.SayHelloReq.content)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SayHelloRsp::kContentFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SayHelloRsp::SayHelloRsp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_say_5fhello_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.Test.SayHelloRsp)
}
SayHelloRsp::SayHelloRsp(const SayHelloRsp& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  content_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.content().size() > 0) {
    content_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.content_);
  }
  // @@protoc_insertion_point(copy_constructor:proto.Test.SayHelloRsp)
}

void SayHelloRsp::SharedCtor() {
  content_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

SayHelloRsp::~SayHelloRsp() {
  // @@protoc_insertion_point(destructor:proto.Test.SayHelloRsp)
  SharedDtor();
}

void SayHelloRsp::SharedDtor() {
  content_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SayHelloRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SayHelloRsp::descriptor() {
  protobuf_say_5fhello_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_say_5fhello_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SayHelloRsp& SayHelloRsp::default_instance() {
  protobuf_say_5fhello_2eproto::InitDefaults();
  return *internal_default_instance();
}

SayHelloRsp* SayHelloRsp::New(::google::protobuf::Arena* arena) const {
  SayHelloRsp* n = new SayHelloRsp;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SayHelloRsp::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.Test.SayHelloRsp)
  content_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool SayHelloRsp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.Test.SayHelloRsp)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string content = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_content()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->content().data(), this->content().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "proto.Test.SayHelloRsp.content"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.Test.SayHelloRsp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.Test.SayHelloRsp)
  return false;
#undef DO_
}

void SayHelloRsp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.Test.SayHelloRsp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string content = 1;
  if (this->content().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->content().data(), this->content().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.Test.SayHelloRsp.content");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->content(), output);
  }

  // @@protoc_insertion_point(serialize_end:proto.Test.SayHelloRsp)
}

::google::protobuf::uint8* SayHelloRsp::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:proto.Test.SayHelloRsp)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string content = 1;
  if (this->content().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->content().data(), this->content().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "proto.Test.SayHelloRsp.content");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->content(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:proto.Test.SayHelloRsp)
  return target;
}

size_t SayHelloRsp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.Test.SayHelloRsp)
  size_t total_size = 0;

  // string content = 1;
  if (this->content().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->content());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SayHelloRsp::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.Test.SayHelloRsp)
  GOOGLE_DCHECK_NE(&from, this);
  const SayHelloRsp* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SayHelloRsp>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.Test.SayHelloRsp)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.Test.SayHelloRsp)
    MergeFrom(*source);
  }
}

void SayHelloRsp::MergeFrom(const SayHelloRsp& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.Test.SayHelloRsp)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.content().size() > 0) {

    content_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.content_);
  }
}

void SayHelloRsp::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.Test.SayHelloRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SayHelloRsp::CopyFrom(const SayHelloRsp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.Test.SayHelloRsp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SayHelloRsp::IsInitialized() const {
  return true;
}

void SayHelloRsp::Swap(SayHelloRsp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SayHelloRsp::InternalSwap(SayHelloRsp* other) {
  content_.Swap(&other->content_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SayHelloRsp::GetMetadata() const {
  protobuf_say_5fhello_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_say_5fhello_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SayHelloRsp

// string content = 1;
void SayHelloRsp::clear_content() {
  content_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& SayHelloRsp::content() const {
  // @@protoc_insertion_point(field_get:proto.Test.SayHelloRsp.content)
  return content_.GetNoArena();
}
void SayHelloRsp::set_content(const ::std::string& value) {
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.Test.SayHelloRsp.content)
}
#if LANG_CXX11
void SayHelloRsp::set_content(::std::string&& value) {
  
  content_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.Test.SayHelloRsp.content)
}
#endif
void SayHelloRsp::set_content(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.Test.SayHelloRsp.content)
}
void SayHelloRsp::set_content(const char* value, size_t size) {
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.Test.SayHelloRsp.content)
}
::std::string* SayHelloRsp::mutable_content() {
  
  // @@protoc_insertion_point(field_mutable:proto.Test.SayHelloRsp.content)
  return content_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* SayHelloRsp::release_content() {
  // @@protoc_insertion_point(field_release:proto.Test.SayHelloRsp.content)
  
  return content_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void SayHelloRsp::set_allocated_content(::std::string* content) {
  if (content != NULL) {
    
  } else {
    
  }
  content_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), content);
  // @@protoc_insertion_point(field_set_allocated:proto.Test.SayHelloRsp.content)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace Test
}  // namespace proto

// @@protoc_insertion_point(global_scope)
